name: SkDynmap
author: Skylyxx
main: fr.skylyxx.skdynmap.SkDynmap
version: @version@
api-version: @apiVersion@
description: A Skript addon that let you interact with Dynmap
website: https://skylyxx.github.io/skdynmap
softdepend: [ Skript,dynmap ]
commands:
  skdynmap:
    description: SkDynmap management command
  test:
    description: test