name: Gradle Build
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set up JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
          java-package: jdk
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew clean githubRelease
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: SkDynmap-Github
          path: out/**
